---
# Enviroment
env: dev

# Php
php_fpm_socket: /var/run/php5-fpm.sock
php_memory_limit: 128M
php_date_timezone: Australia/Melbourne
php_max_execution_time: 30
php_upload_max_filesize: 5M

# Nginx
nginx_upload_max_filesize: 10M

# Symfony
site_domain: backbone.local
site_url: backbone.local

# Database
database_name: backbone
database_user: backbone
database_pass: backbone
database_host: localhost

# Mail
mailer_transport:  smtp
mailer_host:       smtp.gmail.com
mailer_user:       kanskje.denne.gang@gmail.com
mailer_password:   sghkasoihzsdnewwa8723rn
mailer_encryption: ssl

# Repository
repo_url: git@github.com:nejibem/neste-gang.com.git
repo_remote: origin
repo_version: master

# Ansible
ansible_ssh_user: vagrant
# ansible_ssh_private_key_file: ''
